apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-sql-proxy-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: template-sql-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: template-sql-proxy
    spec:
      containers:
        - name: {{ .Chart.Name }}-sql-proxy
          image: "{{ .Values.image.sqlProxy.repository }}:{{ .Values.image.sqlProxy.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: service-port
              containerPort: 3306
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "STARTED"
              echo "GCLOUD_SQL_CONNECTION: $GCLOUD_SQL_CONNECTION"
#          args:
#            - echo "STARTED";
#              echo "GCLOUD_SQL_CONNECTION: $GCLOUD_SQL_CONNECTION";
#              /cloud_sql_proxy -instances=$GCLOUD_SQL_CONNECTION=tcp:0.0.0.0:3306 -credential_file=credential.json;
          envFrom:
            - configMapRef:
                name: template-sql-proxy-configmap
          resources:
            requests:
              cpu: "25m"
              memory: "50Mi"
