apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-sql-proxy-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: template-sql-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: template-sql-proxy
    spec:
      containers:
        - name: {{ .Chart.Name }}-sql-proxy
          image: "{{ .Values.image.sqlProxy.repository }}:{{ .Values.image.sqlProxy.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: service-port
              containerPort: 3306
          command:
            - "/bin/sh"
            - "-c"
            - |
              /cloud_sql_proxy -instances=${CLOUD_DB_INSTANCE} -credential_file=/configuration/cloud_sql_service_account.json
          resources:
            requests:
              cpu: "25m"
              memory: "50Mi"
