apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/template/.*
            pathType: Prefix
            backend:
              service:
                name: template-service
                port:
                  number: 80

