apiVersion: batch/v1
kind: Job
metadata:
  name: template-sql-updater-job
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: registry-credential
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.sqlUpdater.repository }}:{{ .Values.image.sqlUpdater.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
