apiVersion: v1
kind: configmap-sql-proxy.yaml
metadata:
  name: template-sql-proxy-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  gcloud_credential.json: |-
    {{ .Values.gcloud.credential | b64enc }}
