apiVersion: v1
kind: Service
metadata:
  name: template-sql-proxy-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: template-sql-proxy
  ports:
    - protocol: TCP
      name: service-port
      port: 3306
      targetPort: 3306
