apiVersion: v1
kind: Service
metadata:
  name: template-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: template
  ports:
    - protocol: TCP
      name: service-port
      port: 80
      targetPort: 8080
