name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Checkout helm-charts repository
        uses: actions/checkout@v2.4.0
        with:
          repository: sebczu/helm-charts
#          path: lol
          ref: master

#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup helm
        uses: azure/setup-helm@v1
        with:
          version: '3.7.1'

      - name: Helm
        run: |
          helm version
          git version
          ls -a
          echo "NEXT"
          cd helm-charts
          ls -a