name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Checkout helm-charts repository
        uses: actions/checkout@v2.4.0
        with:
          repository: sebczu/helm-charts
          path: helm-charts
          ref: master
          fetch-depth: 0

#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup helm
        uses: azure/setup-helm@v1
        with:
          version: '3.7.1'

      - name: Helm
        run: |
          helm version
          git version
          ls -a
          echo "IN HELM-CHARTS"
          cd helm-charts
          touch test.txt
          ls -a
          echo "lets try again"
#          git remote set-url origin https://sebczu:${{ secrets.REPO_TOKEN }}@github.com/sebczu/helm-charts.git
          git remote add origin https://sebczu:${{ secrets.REPO_TOKEN }}@github.com/sebczu/helm-charts.git
          git config --global user.name 'sebczu'
          git config --global user.email 'sebczu@users.noreply.github.com'
          git add .
          git commit -m "test"
          git push
